Django/project/accounts/urls.py
from django.urls import path


from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup, name='signup'),  # 회원가입
  path('login/', views.login, name='login'), # 로그인
  path('profile/', views.profile, name='profile'), #회원정보보기
  path('logout/', views.logout, name='logout'), # 로그아웃
]

Django/project/body_type/urls.py
# body_type/urls.py
from django.urls import path
from .views import predict_body_type

app_name = 'body_type'

urlpatterns = [
    path("", predict_body_type, name="body_type_home"),  # 기본 페이지를 predict_body_type으로 설정
    path("predict/", predict_body_type, name="predict_body_type"),
]

Django/project/diet_recommendation/urls.py
from django.urls import path
from . import views

app_name = 'diet'

urlpatterns = [
    path('', views.diet_input, name='diet_input'),
]

Django/project/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

Django/project/pose_analysis/urls.py
from django.urls import path
from . import views  # pose_analysis/views.py 가져오기

app_name = 'pose'
urlpatterns = [
    path('', views.pose_home, name='home'),  # 운동 자세 분석 메인 페이지
    path('pose_preview/', views.pose_preview, name='preview'),
    path('pose_workout_select/', views.pose_workout_select, name='workout_select'),
    path('pose_predict/', views.pose_predict, name='predict'),
]

Django/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  # home을 별도 앱으로 분리 (추천)
    path("body_type/", include("body_type.urls")),
    path('diet/', include('diet_recommendation.urls')),
    path('pose/', include('pose_analysis.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/project/home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

Django/project/home/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    /* * * * * footer * * * * * */
    footer{
        margin:5px auto;
        height: 150px;
        overflow: hidden;
    }
    footer div:last-child{
        height:50px; line-height:50px; text-align:center;
        background-color:black;
        color:white;
        position: absolute;
        bottom: 0;
        width:100%;
    }
  </style>
  <title>Title</title>
</head>
<body>
  <footer>
    <div class="copyright">{{ year }}Copyright ⓒ Joeun System Corp. All rights reserved.</div>
  </footer>
</body>
</html>

Django/project/home/templates/header.html
<nav class="navbar navbar-default">
    <div class="container">
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="{% if request.path == '/body_type/' %}active{% endif %}">
                    <a href="{% url 'body_type:body_type_home' %}">체형 분석</a>
                </li>
                <li class="{% if request.path == '/diet/' %}active{% endif %}">
                    <a href="{% url 'diet:diet_input' %}">식단 추천</a>
                </li>
                <li class="{% if request.path == '/pose/' %}active{% endif %}">
                    <a href="{% url 'pose:home' %}">자세 분석</a>
                </li>

                {% if user.is_authenticated %}
                    <li><a href="#">{{ user }}님</a></li>
                    <li><a href="{% url 'accounts:profile' %}">프로필</a></li>
                    <li><a href="{% url 'accounts:logout' %}">로그아웃</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:signup' %}">회원 가입</a></li>
                    <li><a href="{% url 'accounts:login' %}">로그인</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

Django/project/home/templates/home.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>메인 페이지</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
     <div class="logo-container">
        <img src="{% static 'img/logo.png' %}" alt="로고" class="logo">
    </div>
    {% include "header.html" %}

    <div class="button-container">
        <div class="btn-wrapper">
            <div class="btn-text">체형 예측</div>
        <a href="/body_type/" class="btn" style="background-image: url('{% static 'img/body.png' %}');"></a>
        </div>
        <div class="btn-wrapper">
            <div class="btn-text">식단 추천</div>
        <a href="/diet/" class="btn" style="background-image: url('{% static 'img/food.png' %}');"></a>
        </div>
        <div class="btn-wrapper">
            <div class="btn-text">운동 자세 분석</div>
        <a href="/pose/" class="btn" style="background-image: url('{% static 'img/pose.png' %}');"></a>
        </div>
    </div>
    {% include "footer.html" with year=2025 %}
</body>